# Generated by Django 4.0.3 on 2022-04-04 01:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE SCHEMA movie;
            """
        ),
    ]
